<?php

namespace Database\Seeders;

use Laymont\Shicontstand\Models\TypeGroup;

class TypeGroupSeeder extends \Illuminate\Database\Seeder
{
    public function run()
    {
        collect([
            ['code' => '20GP', 'description' => 'GENERAL PURPOSE CONT.'],
            ['code' => '20G1', 'description' => 'GENERAL PURPOSE CONT.'],
            ['code' => '20HR', 'description' => 'ISOLADO CONTAINE REEFER'],
            ['code' => '20PF', 'description' => 'FLAT (FIXED ENDS)'],
            ['code' => '20TD', 'description' => 'TANK CONTAINER'],
            ['code' => '20T4', 'description' => 'TANK CONTAINER'],
            ['code' => '20T5', 'description' => 'TANK CONTAINER'],
            ['code' => '20T6', 'description' => 'TANK CONTAINER'],
            ['code' => '20TG', 'description' => 'TANK CONTAINER'],
            ['code' => '20T8', 'description' => 'TANK CONTAINER'],
            ['code' => '20TN', 'description' => 'TANK CONTAINER'],
            ['code' => '20T1', 'description' => 'TANK CONTAINER'],
            ['code' => '20T2', 'description' => 'TANK CONTAINER'],
            ['code' => '22BU', 'description' => 'BULK CONTAINER'],
            ['code' => '22GP', 'description' => 'GENERAL PURPOSE CONT.'],
            ['code' => '22G1', 'description' => 'GENERAL PURPOSE CONT.'],
            ['code' => '22HR', 'description' => 'INSULATED CONTAINER'],
            ['code' => '22PC', 'description' => 'FLAT (COLLAPSIBLE)'],
            ['code' => '22P8', 'description' => 'FLAT (COLL.FLUSH FOLDING)'],
            ['code' => '22P9', 'description' => 'FLAT (COLLAPSIBLE)'],
            ['code' => '22PF', 'description' => 'FLAT (FIXED ENDS)'],
            ['code' => '22P7', 'description' => 'FLAT (GENSET CARRIER)'],
            ['code' => '22RC', 'description' => 'REEFER CONT.(NO FOOD)'],
            ['code' => '22RS', 'description' => 'BUILT-IN GEN. F. POWER SPLY OF REEF'],
            ['code' => '22RT', 'description' => 'REEFER CONTAINER'],
            ['code' => '22SN', 'description' => 'NAMED CARGO CONTAINER'],
            ['code' => '22TD', 'description' => 'TANK CONTAINER'],
            ['code' => '22T4', 'description' => 'TANK CONTAINER'],
            ['code' => '22T5', 'description' => 'TANK CONTAINER'],
            ['code' => '22T6', 'description' => 'TANK CONTAINER'],
            ['code' => '22TG', 'description' => 'TANK CONTAINER'],
            ['code' => '22T8', 'description' => 'TANK CONTAINER'],
            ['code' => '22TN', 'description' => 'TANK CONTAINER'],
            ['code' => '22T1', 'description' => 'TANK CONTAINER'],
            ['code' => '22T2', 'description' => 'TANK CONTAINER'],
            ['code' => '22UP', 'description' => 'HARDTOP CONTAINER'],
            ['code' => '22UT', 'description' => 'OPEN TOP CONTAINER'],
            ['code' => '22VH', 'description' => 'VENTILATED CONTAINER'],
            ['code' => '22V2', 'description' => 'VENTILATED CONTAINER'],
            ['code' => '22V3', 'description' => 'VENTILATED CONTAINER'],
            ['code' => '25GP', 'description' => 'GP-CONTAINER OVER-HEIGHT'],
            ['code' => '26GP', 'description' => 'GP-CONTAINER OVER-HEIGHT'],
            ['code' => '26HR', 'description' => 'INSULATED CONTAINER'],
            ['code' => '28TG', 'description' => 'TANK FOR GAS'],
            ['code' => '28UT', 'description' => 'OPEN TOP (HALF HEIGHT)'],
            ['code' => '28VH', 'description' => 'VE-HALF-HEIGHT =1448 MM HEIGHT'],
            ['code' => '29PL', 'description' => 'PLATFORM'],
            ['code' => '2EGP', 'description' => 'GEN. PURP. WITHOUT VENT WIDTH 2.5M'],
            ['code' => '42GP', 'description' => 'GENERAL PURPOSE CONT.'],
            ['code' => '42G1', 'description' => 'GENERAL PURPOSE CONT.'],
            ['code' => '42HR', 'description' => 'INSULATED CONTAINER'],
            ['code' => '42PC', 'description' => 'FLAT (COLLAPSIBLE)'],
            ['code' => '42P8', 'description' => 'FLAT (COLL.FLUSH FOLDING)'],
            ['code' => '42P9', 'description' => 'FLAT (COLLAPSIBLE)'],
            ['code' => '42PF', 'description' => 'FLAT (FIXED ENDS)'],
            ['code' => '42PS', 'description' => 'FLAT (SPACE SAVER)'],
            ['code' => '42RC', 'description' => 'REEFER CONT.(NO FOOD)'],
            ['code' => '42RS', 'description' => 'REEFER CONT.(DIESEL GEN.)'],
            ['code' => '42RT', 'description' => 'REEFER CONTAINER'],
            ['code' => '42SN', 'description' => 'NAMED CARGO CONTAINER'],
            ['code' => '42TD', 'description' => 'TANK CONTAINER'],
            ['code' => '42T6', 'description' => 'TANK CONTAINER'],
            ['code' => '42TG', 'description' => 'TANK CONTAINER'],
            ['code' => '42TN', 'description' => 'TANK CONTAINER'],
            ['code' => '42UP', 'description' => 'HARDTOP CONTAINER'],
            ['code' => '42UT', 'description' => 'OPEN TOP CONTAINER'],
            ['code' => '45BK', 'description' => 'BULK CONTAINER'],
            ['code' => '45GP', 'description' => 'HIGH CUBE CONT.'],
            ['code' => '45G1', 'description' => 'HIGH CUBE CONT.'],
            ['code' => '45PC', 'description' => 'FLAT (COLLAPSIBLE)'],
            ['code' => '45P8', 'description' => 'FLAT (COLL.FLUSH FOLDING)'],
            ['code' => '45RC', 'description' => 'REEFER CONT.(NO FOOD)'],
            ['code' => '45RT', 'description' => 'REEFER HIGHCUBE CONTAINER'],
            ['code' => '45UT', 'description' => 'OPEN TOP CONTAINER'],
            ['code' => '45UP', 'description' => 'HIGH CUBE HARDTOP CONT.'],
            ['code' => '46HR', 'description' => 'INSULATED CONTAINER'],
            ['code' => '48TG', 'description' => 'TANK FOR GAS'],
            ['code' => '49PL', 'description' => 'PLATFORM'],
            ['code' => '4CGP', 'description' => 'GP CONTAINER'],
            ['code' => 'L0GP', 'description' => 'HIGH CUBE CONT.'],
            ['code' => 'L2GP', 'description' => 'HIGH CUBE CONT.'],
            ['code' => 'L5GP', 'description' => 'HIGH CUBE CONT.'],

        ])->each(fn ($item) => TypeGroup::create($item));
    }
}
