<?php

namespace Laymont\Shicontstand;

use Illuminate\Support\Facades\Facade;

class ShicontstandFacade extends Facade
{
    protected static function getFacadeAccessor(): string
    {
        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub

        return 'scs';
    }
}
