<?php

namespace Laymont\Shicontstand;

class ShicontstandFacade extends \Illuminate\Support\Facades\Facade
{
    protected static function getFacadeAccessor(): string
    {
        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub

        return 'scs';
    }
}
