services:
#    acme.demo.example:
#        class:     Acme\DemoBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
#        calls:
#            - [setService, ["@service_id"]]
#        tags:
#            - { name: twig.extension }
#            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
  - name: Changelog Generator
    uses: timfallmk/github-changelog-generator-action@0.0.2
